//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Admin {
    
    
    public partial class FoodTypeManager {
        
        /// <summary>
        /// OfficePopupNewFoodType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OfficeWebUI.OfficePopup OfficePopupNewFoodType;
        
        /// <summary>
        /// NewFoodTypeName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox NewFoodTypeName;
        
        /// <summary>
        /// OfficeMessageBoxAddFoodTypeSuccess control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OfficeWebUI.OfficeMessageBox OfficeMessageBoxAddFoodTypeSuccess;
        
        /// <summary>
        /// OfficeMessageBoxAddFoodTypeFail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OfficeWebUI.OfficeMessageBox OfficeMessageBoxAddFoodTypeFail;
        
        /// <summary>
        /// OfficeMessageBoxUpdateFoodTypeSuccess control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OfficeWebUI.OfficeMessageBox OfficeMessageBoxUpdateFoodTypeSuccess;
        
        /// <summary>
        /// OfficeMessageBoxUpdateFoodTypeFail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OfficeWebUI.OfficeMessageBox OfficeMessageBoxUpdateFoodTypeFail;
        
        /// <summary>
        /// OfficeMessageBoxConfirmDelete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OfficeWebUI.OfficeMessageBox OfficeMessageBoxConfirmDelete;
        
        /// <summary>
        /// OfficeMessageBoxConfirmEdit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OfficeWebUI.OfficeMessageBox OfficeMessageBoxConfirmEdit;
        
        /// <summary>
        /// GridViewListFoodType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView GridViewListFoodType;
    }
}
