//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("FoodStoreModel", "FK_ACCOUNT_QUESTION", "QUESTION", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Model.QUESTION), "ACCOUNT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Model.ACCOUNT), true)]
[assembly: EdmRelationshipAttribute("FoodStoreModel", "FK_ORDER_ACCOUNT", "ACCOUNT", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Model.ACCOUNT), "ORDER", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Model.ORDER), true)]
[assembly: EdmRelationshipAttribute("FoodStoreModel", "FK_BILLDETAIL_BILL1", "BILL", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Model.BILL), "BILLDETAIL", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Model.BILLDETAIL), true)]
[assembly: EdmRelationshipAttribute("FoodStoreModel", "FK_ORDER_BILL1", "BILL", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Model.BILL), "ORDER", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Model.ORDER), true)]
[assembly: EdmRelationshipAttribute("FoodStoreModel", "FK_BILLDETAIL_FOOD1", "FOOD", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Model.FOOD), "BILLDETAIL", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Model.BILLDETAIL), true)]
[assembly: EdmRelationshipAttribute("FoodStoreModel", "FK_FOOD_FOODTYPE1", "FOODTYPE", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Model.FOODTYPE), "FOOD", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Model.FOOD), true)]
[assembly: EdmRelationshipAttribute("FoodStoreModel", "FK_ORDERDETAIL_FOOD1", "FOOD", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Model.FOOD), "ORDERDETAIL", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Model.ORDERDETAIL), true)]
[assembly: EdmRelationshipAttribute("FoodStoreModel", "FK_ORDERDETAIL_ORDER1", "ORDER", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Model.ORDER), "ORDERDETAIL", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Model.ORDERDETAIL), true)]
[assembly: EdmRelationshipAttribute("FoodStoreModel", "FK_ACCOUNT_CITY", "CITY", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Model.CITY), "ACCOUNT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Model.ACCOUNT), true)]
[assembly: EdmRelationshipAttribute("FoodStoreModel", "FK_ACCOUNT_DISTRICT", "DISTRICT", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Model.DISTRICT), "ACCOUNT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Model.ACCOUNT), true)]
[assembly: EdmRelationshipAttribute("FoodStoreModel", "FK_DISTRICT_CITY", "CITY", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Model.CITY), "DISTRICT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Model.DISTRICT), true)]
[assembly: EdmRelationshipAttribute("FoodStoreModel", "FK_ORDER_CITY", "CITY", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Model.CITY), "ORDER", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Model.ORDER), true)]
[assembly: EdmRelationshipAttribute("FoodStoreModel", "FK_ORDER_DISTRICT", "DISTRICT", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Model.DISTRICT), "ORDER", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Model.ORDER), true)]

#endregion

namespace Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FoodStoreEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FoodStoreEntities object using the connection string found in the 'FoodStoreEntities' section of the application configuration file.
        /// </summary>
        public FoodStoreEntities() : base("name=FoodStoreEntities", "FoodStoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FoodStoreEntities object.
        /// </summary>
        public FoodStoreEntities(string connectionString) : base(connectionString, "FoodStoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FoodStoreEntities object.
        /// </summary>
        public FoodStoreEntities(EntityConnection connection) : base(connection, "FoodStoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ACCOUNT> ACCOUNTs
        {
            get
            {
                if ((_ACCOUNTs == null))
                {
                    _ACCOUNTs = base.CreateObjectSet<ACCOUNT>("ACCOUNTs");
                }
                return _ACCOUNTs;
            }
        }
        private ObjectSet<ACCOUNT> _ACCOUNTs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BILL> BILLs
        {
            get
            {
                if ((_BILLs == null))
                {
                    _BILLs = base.CreateObjectSet<BILL>("BILLs");
                }
                return _BILLs;
            }
        }
        private ObjectSet<BILL> _BILLs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BILLDETAIL> BILLDETAILs
        {
            get
            {
                if ((_BILLDETAILs == null))
                {
                    _BILLDETAILs = base.CreateObjectSet<BILLDETAIL>("BILLDETAILs");
                }
                return _BILLDETAILs;
            }
        }
        private ObjectSet<BILLDETAIL> _BILLDETAILs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FOOD> FOODs
        {
            get
            {
                if ((_FOODs == null))
                {
                    _FOODs = base.CreateObjectSet<FOOD>("FOODs");
                }
                return _FOODs;
            }
        }
        private ObjectSet<FOOD> _FOODs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FOODTYPE> FOODTYPEs
        {
            get
            {
                if ((_FOODTYPEs == null))
                {
                    _FOODTYPEs = base.CreateObjectSet<FOODTYPE>("FOODTYPEs");
                }
                return _FOODTYPEs;
            }
        }
        private ObjectSet<FOODTYPE> _FOODTYPEs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ORDER> ORDERs
        {
            get
            {
                if ((_ORDERs == null))
                {
                    _ORDERs = base.CreateObjectSet<ORDER>("ORDERs");
                }
                return _ORDERs;
            }
        }
        private ObjectSet<ORDER> _ORDERs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ORDERDETAIL> ORDERDETAILs
        {
            get
            {
                if ((_ORDERDETAILs == null))
                {
                    _ORDERDETAILs = base.CreateObjectSet<ORDERDETAIL>("ORDERDETAILs");
                }
                return _ORDERDETAILs;
            }
        }
        private ObjectSet<ORDERDETAIL> _ORDERDETAILs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<QUESTION> QUESTIONs
        {
            get
            {
                if ((_QUESTIONs == null))
                {
                    _QUESTIONs = base.CreateObjectSet<QUESTION>("QUESTIONs");
                }
                return _QUESTIONs;
            }
        }
        private ObjectSet<QUESTION> _QUESTIONs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CITY> CITies
        {
            get
            {
                if ((_CITies == null))
                {
                    _CITies = base.CreateObjectSet<CITY>("CITies");
                }
                return _CITies;
            }
        }
        private ObjectSet<CITY> _CITies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DISTRICT> DISTRICTs
        {
            get
            {
                if ((_DISTRICTs == null))
                {
                    _DISTRICTs = base.CreateObjectSet<DISTRICT>("DISTRICTs");
                }
                return _DISTRICTs;
            }
        }
        private ObjectSet<DISTRICT> _DISTRICTs;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ACCOUNTs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToACCOUNTs(ACCOUNT aCCOUNT)
        {
            base.AddObject("ACCOUNTs", aCCOUNT);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BILLs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBILLs(BILL bILL)
        {
            base.AddObject("BILLs", bILL);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BILLDETAILs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBILLDETAILs(BILLDETAIL bILLDETAIL)
        {
            base.AddObject("BILLDETAILs", bILLDETAIL);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FOODs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFOODs(FOOD fOOD)
        {
            base.AddObject("FOODs", fOOD);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FOODTYPEs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFOODTYPEs(FOODTYPE fOODTYPE)
        {
            base.AddObject("FOODTYPEs", fOODTYPE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ORDERs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToORDERs(ORDER oRDER)
        {
            base.AddObject("ORDERs", oRDER);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ORDERDETAILs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToORDERDETAILs(ORDERDETAIL oRDERDETAIL)
        {
            base.AddObject("ORDERDETAILs", oRDERDETAIL);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the QUESTIONs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQUESTIONs(QUESTION qUESTION)
        {
            base.AddObject("QUESTIONs", qUESTION);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CITies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCITies(CITY cITY)
        {
            base.AddObject("CITies", cITY);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DISTRICTs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDISTRICTs(DISTRICT dISTRICT)
        {
            base.AddObject("DISTRICTs", dISTRICT);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FoodStoreModel", Name="ACCOUNT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ACCOUNT : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ACCOUNT object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static ACCOUNT CreateACCOUNT(global::System.Int32 id)
        {
            ACCOUNT aCCOUNT = new ACCOUNT();
            aCCOUNT.ID = id;
            return aCCOUNT;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tel
        {
            get
            {
                return _Tel;
            }
            set
            {
                OnTelChanging(value);
                ReportPropertyChanging("Tel");
                _Tel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tel");
                OnTelChanged();
            }
        }
        private global::System.String _Tel;
        partial void OnTelChanging(global::System.String value);
        partial void OnTelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SocialID
        {
            get
            {
                return _SocialID;
            }
            set
            {
                OnSocialIDChanging(value);
                ReportPropertyChanging("SocialID");
                _SocialID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SocialID");
                OnSocialIDChanged();
            }
        }
        private global::System.String _SocialID;
        partial void OnSocialIDChanging(global::System.String value);
        partial void OnSocialIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Question
        {
            get
            {
                return _Question;
            }
            set
            {
                OnQuestionChanging(value);
                ReportPropertyChanging("Question");
                _Question = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Question");
                OnQuestionChanged();
            }
        }
        private Nullable<global::System.Int32> _Question;
        partial void OnQuestionChanging(Nullable<global::System.Int32> value);
        partial void OnQuestionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Answer
        {
            get
            {
                return _Answer;
            }
            set
            {
                OnAnswerChanging(value);
                ReportPropertyChanging("Answer");
                _Answer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Answer");
                OnAnswerChanged();
            }
        }
        private global::System.String _Answer;
        partial void OnAnswerChanging(global::System.String value);
        partial void OnAnswerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDCity
        {
            get
            {
                return _IDCity;
            }
            set
            {
                OnIDCityChanging(value);
                ReportPropertyChanging("IDCity");
                _IDCity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDCity");
                OnIDCityChanged();
            }
        }
        private Nullable<global::System.Int32> _IDCity;
        partial void OnIDCityChanging(Nullable<global::System.Int32> value);
        partial void OnIDCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDDistrict
        {
            get
            {
                return _IDDistrict;
            }
            set
            {
                OnIDDistrictChanging(value);
                ReportPropertyChanging("IDDistrict");
                _IDDistrict = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDDistrict");
                OnIDDistrictChanged();
            }
        }
        private Nullable<global::System.Int32> _IDDistrict;
        partial void OnIDDistrictChanging(Nullable<global::System.Int32> value);
        partial void OnIDDistrictChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_ACCOUNT_QUESTION", "QUESTION")]
        public QUESTION QUESTION
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QUESTION>("FoodStoreModel.FK_ACCOUNT_QUESTION", "QUESTION").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QUESTION>("FoodStoreModel.FK_ACCOUNT_QUESTION", "QUESTION").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<QUESTION> QUESTIONReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QUESTION>("FoodStoreModel.FK_ACCOUNT_QUESTION", "QUESTION");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<QUESTION>("FoodStoreModel.FK_ACCOUNT_QUESTION", "QUESTION", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_ORDER_ACCOUNT", "ORDER")]
        public EntityCollection<ORDER> ORDERs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ORDER>("FoodStoreModel.FK_ORDER_ACCOUNT", "ORDER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ORDER>("FoodStoreModel.FK_ORDER_ACCOUNT", "ORDER", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_ACCOUNT_CITY", "CITY")]
        public CITY CITY
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CITY>("FoodStoreModel.FK_ACCOUNT_CITY", "CITY").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CITY>("FoodStoreModel.FK_ACCOUNT_CITY", "CITY").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CITY> CITYReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CITY>("FoodStoreModel.FK_ACCOUNT_CITY", "CITY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CITY>("FoodStoreModel.FK_ACCOUNT_CITY", "CITY", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_ACCOUNT_DISTRICT", "DISTRICT")]
        public DISTRICT DISTRICT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DISTRICT>("FoodStoreModel.FK_ACCOUNT_DISTRICT", "DISTRICT").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DISTRICT>("FoodStoreModel.FK_ACCOUNT_DISTRICT", "DISTRICT").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DISTRICT> DISTRICTReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DISTRICT>("FoodStoreModel.FK_ACCOUNT_DISTRICT", "DISTRICT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DISTRICT>("FoodStoreModel.FK_ACCOUNT_DISTRICT", "DISTRICT", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FoodStoreModel", Name="BILL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BILL : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BILL object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static BILL CreateBILL(global::System.Int32 id)
        {
            BILL bILL = new BILL();
            bILL.ID = id;
            return bILL;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TotalPayment
        {
            get
            {
                return _TotalPayment;
            }
            set
            {
                OnTotalPaymentChanging(value);
                ReportPropertyChanging("TotalPayment");
                _TotalPayment = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalPayment");
                OnTotalPaymentChanged();
            }
        }
        private Nullable<global::System.Int32> _TotalPayment;
        partial void OnTotalPaymentChanging(Nullable<global::System.Int32> value);
        partial void OnTotalPaymentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Note
        {
            get
            {
                return _Note;
            }
            set
            {
                OnNoteChanging(value);
                ReportPropertyChanging("Note");
                _Note = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Note");
                OnNoteChanged();
            }
        }
        private global::System.String _Note;
        partial void OnNoteChanging(global::System.String value);
        partial void OnNoteChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_BILLDETAIL_BILL1", "BILLDETAIL")]
        public EntityCollection<BILLDETAIL> BILLDETAILs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BILLDETAIL>("FoodStoreModel.FK_BILLDETAIL_BILL1", "BILLDETAIL");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BILLDETAIL>("FoodStoreModel.FK_BILLDETAIL_BILL1", "BILLDETAIL", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_ORDER_BILL1", "ORDER")]
        public ORDER ORDER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ORDER>("FoodStoreModel.FK_ORDER_BILL1", "ORDER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ORDER>("FoodStoreModel.FK_ORDER_BILL1", "ORDER").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ORDER> ORDERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ORDER>("FoodStoreModel.FK_ORDER_BILL1", "ORDER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ORDER>("FoodStoreModel.FK_ORDER_BILL1", "ORDER", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FoodStoreModel", Name="BILLDETAIL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BILLDETAIL : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BILLDETAIL object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="food">Initial value of the Food property.</param>
        public static BILLDETAIL CreateBILLDETAIL(global::System.Int32 id, global::System.Int32 food)
        {
            BILLDETAIL bILLDETAIL = new BILLDETAIL();
            bILLDETAIL.ID = id;
            bILLDETAIL.Food = food;
            return bILLDETAIL;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Food
        {
            get
            {
                return _Food;
            }
            set
            {
                if (_Food != value)
                {
                    OnFoodChanging(value);
                    ReportPropertyChanging("Food");
                    _Food = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Food");
                    OnFoodChanged();
                }
            }
        }
        private global::System.Int32 _Food;
        partial void OnFoodChanging(global::System.Int32 value);
        partial void OnFoodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Count
        {
            get
            {
                return _Count;
            }
            set
            {
                OnCountChanging(value);
                ReportPropertyChanging("Count");
                _Count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Count");
                OnCountChanged();
            }
        }
        private Nullable<global::System.Int32> _Count;
        partial void OnCountChanging(Nullable<global::System.Int32> value);
        partial void OnCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Int32> _Price;
        partial void OnPriceChanging(Nullable<global::System.Int32> value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TotalPayment
        {
            get
            {
                return _TotalPayment;
            }
            set
            {
                OnTotalPaymentChanging(value);
                ReportPropertyChanging("TotalPayment");
                _TotalPayment = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalPayment");
                OnTotalPaymentChanged();
            }
        }
        private Nullable<global::System.Int32> _TotalPayment;
        partial void OnTotalPaymentChanging(Nullable<global::System.Int32> value);
        partial void OnTotalPaymentChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_BILLDETAIL_BILL1", "BILL")]
        public BILL BILL
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BILL>("FoodStoreModel.FK_BILLDETAIL_BILL1", "BILL").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BILL>("FoodStoreModel.FK_BILLDETAIL_BILL1", "BILL").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BILL> BILLReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BILL>("FoodStoreModel.FK_BILLDETAIL_BILL1", "BILL");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BILL>("FoodStoreModel.FK_BILLDETAIL_BILL1", "BILL", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_BILLDETAIL_FOOD1", "FOOD")]
        public FOOD FOOD
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FOOD>("FoodStoreModel.FK_BILLDETAIL_FOOD1", "FOOD").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FOOD>("FoodStoreModel.FK_BILLDETAIL_FOOD1", "FOOD").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FOOD> FOODReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FOOD>("FoodStoreModel.FK_BILLDETAIL_FOOD1", "FOOD");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FOOD>("FoodStoreModel.FK_BILLDETAIL_FOOD1", "FOOD", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FoodStoreModel", Name="CITY")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CITY : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CITY object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static CITY CreateCITY(global::System.Int32 id)
        {
            CITY cITY = new CITY();
            cITY.ID = id;
            return cITY;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_ACCOUNT_CITY", "ACCOUNT")]
        public EntityCollection<ACCOUNT> ACCOUNTs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ACCOUNT>("FoodStoreModel.FK_ACCOUNT_CITY", "ACCOUNT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ACCOUNT>("FoodStoreModel.FK_ACCOUNT_CITY", "ACCOUNT", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_DISTRICT_CITY", "DISTRICT")]
        public EntityCollection<DISTRICT> DISTRICTs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DISTRICT>("FoodStoreModel.FK_DISTRICT_CITY", "DISTRICT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DISTRICT>("FoodStoreModel.FK_DISTRICT_CITY", "DISTRICT", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_ORDER_CITY", "ORDER")]
        public EntityCollection<ORDER> ORDERs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ORDER>("FoodStoreModel.FK_ORDER_CITY", "ORDER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ORDER>("FoodStoreModel.FK_ORDER_CITY", "ORDER", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FoodStoreModel", Name="DISTRICT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DISTRICT : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DISTRICT object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static DISTRICT CreateDISTRICT(global::System.Int32 id)
        {
            DISTRICT dISTRICT = new DISTRICT();
            dISTRICT.ID = id;
            return dISTRICT;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDCity
        {
            get
            {
                return _IDCity;
            }
            set
            {
                OnIDCityChanging(value);
                ReportPropertyChanging("IDCity");
                _IDCity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDCity");
                OnIDCityChanged();
            }
        }
        private Nullable<global::System.Int32> _IDCity;
        partial void OnIDCityChanging(Nullable<global::System.Int32> value);
        partial void OnIDCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_ACCOUNT_DISTRICT", "ACCOUNT")]
        public EntityCollection<ACCOUNT> ACCOUNTs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ACCOUNT>("FoodStoreModel.FK_ACCOUNT_DISTRICT", "ACCOUNT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ACCOUNT>("FoodStoreModel.FK_ACCOUNT_DISTRICT", "ACCOUNT", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_DISTRICT_CITY", "CITY")]
        public CITY CITY
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CITY>("FoodStoreModel.FK_DISTRICT_CITY", "CITY").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CITY>("FoodStoreModel.FK_DISTRICT_CITY", "CITY").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CITY> CITYReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CITY>("FoodStoreModel.FK_DISTRICT_CITY", "CITY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CITY>("FoodStoreModel.FK_DISTRICT_CITY", "CITY", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_ORDER_DISTRICT", "ORDER")]
        public EntityCollection<ORDER> ORDERs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ORDER>("FoodStoreModel.FK_ORDER_DISTRICT", "ORDER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ORDER>("FoodStoreModel.FK_ORDER_DISTRICT", "ORDER", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FoodStoreModel", Name="FOOD")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FOOD : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FOOD object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static FOOD CreateFOOD(global::System.Int32 id)
        {
            FOOD fOOD = new FOOD();
            fOOD.ID = id;
            return fOOD;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Int32> _Price;
        partial void OnPriceChanging(Nullable<global::System.Int32> value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Detail
        {
            get
            {
                return _Detail;
            }
            set
            {
                OnDetailChanging(value);
                ReportPropertyChanging("Detail");
                _Detail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Detail");
                OnDetailChanged();
            }
        }
        private global::System.String _Detail;
        partial void OnDetailChanging(global::System.String value);
        partial void OnDetailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Image
        {
            get
            {
                return _Image;
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.String _Image;
        partial void OnImageChanging(global::System.String value);
        partial void OnImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FoodType
        {
            get
            {
                return _FoodType;
            }
            set
            {
                OnFoodTypeChanging(value);
                ReportPropertyChanging("FoodType");
                _FoodType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FoodType");
                OnFoodTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _FoodType;
        partial void OnFoodTypeChanging(Nullable<global::System.Int32> value);
        partial void OnFoodTypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_BILLDETAIL_FOOD1", "BILLDETAIL")]
        public EntityCollection<BILLDETAIL> BILLDETAILs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BILLDETAIL>("FoodStoreModel.FK_BILLDETAIL_FOOD1", "BILLDETAIL");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BILLDETAIL>("FoodStoreModel.FK_BILLDETAIL_FOOD1", "BILLDETAIL", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_FOOD_FOODTYPE1", "FOODTYPE")]
        public FOODTYPE FOODTYPE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FOODTYPE>("FoodStoreModel.FK_FOOD_FOODTYPE1", "FOODTYPE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FOODTYPE>("FoodStoreModel.FK_FOOD_FOODTYPE1", "FOODTYPE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FOODTYPE> FOODTYPEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FOODTYPE>("FoodStoreModel.FK_FOOD_FOODTYPE1", "FOODTYPE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FOODTYPE>("FoodStoreModel.FK_FOOD_FOODTYPE1", "FOODTYPE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_ORDERDETAIL_FOOD1", "ORDERDETAIL")]
        public EntityCollection<ORDERDETAIL> ORDERDETAILs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ORDERDETAIL>("FoodStoreModel.FK_ORDERDETAIL_FOOD1", "ORDERDETAIL");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ORDERDETAIL>("FoodStoreModel.FK_ORDERDETAIL_FOOD1", "ORDERDETAIL", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FoodStoreModel", Name="FOODTYPE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FOODTYPE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FOODTYPE object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static FOODTYPE CreateFOODTYPE(global::System.Int32 id)
        {
            FOODTYPE fOODTYPE = new FOODTYPE();
            fOODTYPE.ID = id;
            return fOODTYPE;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_FOOD_FOODTYPE1", "FOOD")]
        public EntityCollection<FOOD> FOODs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FOOD>("FoodStoreModel.FK_FOOD_FOODTYPE1", "FOOD");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FOOD>("FoodStoreModel.FK_FOOD_FOODTYPE1", "FOOD", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FoodStoreModel", Name="ORDER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ORDER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ORDER object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static ORDER CreateORDER(global::System.Int32 id)
        {
            ORDER oRDER = new ORDER();
            oRDER.ID = id;
            return oRDER;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private Nullable<global::System.Int32> _UserName;
        partial void OnUserNameChanging(Nullable<global::System.Int32> value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Guest
        {
            get
            {
                return _Guest;
            }
            set
            {
                OnGuestChanging(value);
                ReportPropertyChanging("Guest");
                _Guest = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Guest");
                OnGuestChanged();
            }
        }
        private global::System.String _Guest;
        partial void OnGuestChanging(global::System.String value);
        partial void OnGuestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tel
        {
            get
            {
                return _Tel;
            }
            set
            {
                OnTelChanging(value);
                ReportPropertyChanging("Tel");
                _Tel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tel");
                OnTelChanged();
            }
        }
        private global::System.String _Tel;
        partial void OnTelChanging(global::System.String value);
        partial void OnTelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Note
        {
            get
            {
                return _Note;
            }
            set
            {
                OnNoteChanging(value);
                ReportPropertyChanging("Note");
                _Note = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Note");
                OnNoteChanged();
            }
        }
        private global::System.String _Note;
        partial void OnNoteChanging(global::System.String value);
        partial void OnNoteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private Nullable<global::System.Int32> _State;
        partial void OnStateChanging(Nullable<global::System.Int32> value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TotalPayment
        {
            get
            {
                return _TotalPayment;
            }
            set
            {
                OnTotalPaymentChanging(value);
                ReportPropertyChanging("TotalPayment");
                _TotalPayment = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalPayment");
                OnTotalPaymentChanged();
            }
        }
        private Nullable<global::System.Int32> _TotalPayment;
        partial void OnTotalPaymentChanging(Nullable<global::System.Int32> value);
        partial void OnTotalPaymentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDCity
        {
            get
            {
                return _IDCity;
            }
            set
            {
                OnIDCityChanging(value);
                ReportPropertyChanging("IDCity");
                _IDCity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDCity");
                OnIDCityChanged();
            }
        }
        private Nullable<global::System.Int32> _IDCity;
        partial void OnIDCityChanging(Nullable<global::System.Int32> value);
        partial void OnIDCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDDistrict
        {
            get
            {
                return _IDDistrict;
            }
            set
            {
                OnIDDistrictChanging(value);
                ReportPropertyChanging("IDDistrict");
                _IDDistrict = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDDistrict");
                OnIDDistrictChanged();
            }
        }
        private Nullable<global::System.Int32> _IDDistrict;
        partial void OnIDDistrictChanging(Nullable<global::System.Int32> value);
        partial void OnIDDistrictChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_ORDER_ACCOUNT", "ACCOUNT")]
        public ACCOUNT ACCOUNT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ACCOUNT>("FoodStoreModel.FK_ORDER_ACCOUNT", "ACCOUNT").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ACCOUNT>("FoodStoreModel.FK_ORDER_ACCOUNT", "ACCOUNT").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ACCOUNT> ACCOUNTReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ACCOUNT>("FoodStoreModel.FK_ORDER_ACCOUNT", "ACCOUNT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ACCOUNT>("FoodStoreModel.FK_ORDER_ACCOUNT", "ACCOUNT", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_ORDER_BILL1", "BILL")]
        public BILL BILL
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BILL>("FoodStoreModel.FK_ORDER_BILL1", "BILL").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BILL>("FoodStoreModel.FK_ORDER_BILL1", "BILL").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BILL> BILLReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BILL>("FoodStoreModel.FK_ORDER_BILL1", "BILL");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BILL>("FoodStoreModel.FK_ORDER_BILL1", "BILL", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_ORDERDETAIL_ORDER1", "ORDERDETAIL")]
        public EntityCollection<ORDERDETAIL> ORDERDETAILs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ORDERDETAIL>("FoodStoreModel.FK_ORDERDETAIL_ORDER1", "ORDERDETAIL");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ORDERDETAIL>("FoodStoreModel.FK_ORDERDETAIL_ORDER1", "ORDERDETAIL", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_ORDER_CITY", "CITY")]
        public CITY CITY
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CITY>("FoodStoreModel.FK_ORDER_CITY", "CITY").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CITY>("FoodStoreModel.FK_ORDER_CITY", "CITY").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CITY> CITYReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CITY>("FoodStoreModel.FK_ORDER_CITY", "CITY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CITY>("FoodStoreModel.FK_ORDER_CITY", "CITY", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_ORDER_DISTRICT", "DISTRICT")]
        public DISTRICT DISTRICT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DISTRICT>("FoodStoreModel.FK_ORDER_DISTRICT", "DISTRICT").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DISTRICT>("FoodStoreModel.FK_ORDER_DISTRICT", "DISTRICT").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DISTRICT> DISTRICTReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DISTRICT>("FoodStoreModel.FK_ORDER_DISTRICT", "DISTRICT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DISTRICT>("FoodStoreModel.FK_ORDER_DISTRICT", "DISTRICT", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FoodStoreModel", Name="ORDERDETAIL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ORDERDETAIL : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ORDERDETAIL object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="food">Initial value of the Food property.</param>
        public static ORDERDETAIL CreateORDERDETAIL(global::System.Int32 id, global::System.Int32 food)
        {
            ORDERDETAIL oRDERDETAIL = new ORDERDETAIL();
            oRDERDETAIL.ID = id;
            oRDERDETAIL.Food = food;
            return oRDERDETAIL;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Food
        {
            get
            {
                return _Food;
            }
            set
            {
                if (_Food != value)
                {
                    OnFoodChanging(value);
                    ReportPropertyChanging("Food");
                    _Food = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Food");
                    OnFoodChanged();
                }
            }
        }
        private global::System.Int32 _Food;
        partial void OnFoodChanging(global::System.Int32 value);
        partial void OnFoodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Count
        {
            get
            {
                return _Count;
            }
            set
            {
                OnCountChanging(value);
                ReportPropertyChanging("Count");
                _Count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Count");
                OnCountChanged();
            }
        }
        private Nullable<global::System.Int32> _Count;
        partial void OnCountChanging(Nullable<global::System.Int32> value);
        partial void OnCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Int32> _Price;
        partial void OnPriceChanging(Nullable<global::System.Int32> value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TotalPayment
        {
            get
            {
                return _TotalPayment;
            }
            set
            {
                OnTotalPaymentChanging(value);
                ReportPropertyChanging("TotalPayment");
                _TotalPayment = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalPayment");
                OnTotalPaymentChanged();
            }
        }
        private Nullable<global::System.Int32> _TotalPayment;
        partial void OnTotalPaymentChanging(Nullable<global::System.Int32> value);
        partial void OnTotalPaymentChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_ORDERDETAIL_FOOD1", "FOOD")]
        public FOOD FOOD
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FOOD>("FoodStoreModel.FK_ORDERDETAIL_FOOD1", "FOOD").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FOOD>("FoodStoreModel.FK_ORDERDETAIL_FOOD1", "FOOD").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FOOD> FOODReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FOOD>("FoodStoreModel.FK_ORDERDETAIL_FOOD1", "FOOD");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FOOD>("FoodStoreModel.FK_ORDERDETAIL_FOOD1", "FOOD", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_ORDERDETAIL_ORDER1", "ORDER")]
        public ORDER ORDER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ORDER>("FoodStoreModel.FK_ORDERDETAIL_ORDER1", "ORDER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ORDER>("FoodStoreModel.FK_ORDERDETAIL_ORDER1", "ORDER").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ORDER> ORDERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ORDER>("FoodStoreModel.FK_ORDERDETAIL_ORDER1", "ORDER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ORDER>("FoodStoreModel.FK_ORDERDETAIL_ORDER1", "ORDER", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FoodStoreModel", Name="QUESTION")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class QUESTION : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new QUESTION object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static QUESTION CreateQUESTION(global::System.Int32 id)
        {
            QUESTION qUESTION = new QUESTION();
            qUESTION.ID = id;
            return qUESTION;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Question
        {
            get
            {
                return _Question;
            }
            set
            {
                OnQuestionChanging(value);
                ReportPropertyChanging("Question");
                _Question = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Question");
                OnQuestionChanged();
            }
        }
        private global::System.String _Question;
        partial void OnQuestionChanging(global::System.String value);
        partial void OnQuestionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodStoreModel", "FK_ACCOUNT_QUESTION", "ACCOUNT")]
        public EntityCollection<ACCOUNT> ACCOUNTs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ACCOUNT>("FoodStoreModel.FK_ACCOUNT_QUESTION", "ACCOUNT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ACCOUNT>("FoodStoreModel.FK_ACCOUNT_QUESTION", "ACCOUNT", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
